"""
Institution directory and EHR platform presets.

The directory lists US health systems with published patient-access FHIR endpoints, one file
per vendor in ``app/data/institutions/`` (Epic, Oracle Health and eClinicalWorks are generated by
``scripts/refresh_directory.py``; ``curated.json`` holds athenahealth's national endpoint, the VA and
the SMART demo). Each platform preset describes how to reach the vendor's developer sandbox.
"""

from __future__ import annotations

import json
from functools import lru_cache
from typing import Any, Optional

from app.core import config

USCDI_SCOPES = (
    "openid fhirUser launch/patient offline_access "
    "patient/Patient.read patient/Observation.read patient/MedicationRequest.read patient/Medication.read "
    "patient/Condition.read patient/AllergyIntolerance.read patient/Immunization.read patient/Encounter.read "
    "patient/Procedure.read patient/DiagnosticReport.read patient/DocumentReference.read patient/Binary.read "
    "patient/CareTeam.read patient/CarePlan.read patient/Goal.read patient/Device.read patient/Coverage.read"
)

PLATFORMS: dict[str, dict[str, Any]] = {
    "epic": {
        "label": "Epic", "portal": "MyChart",
        "sandbox_base": "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4",
        "sandbox_hint": "Epic sandbox test patient: fhircamila / epicepic1",
        "scopes": USCDI_SCOPES,
        # Epic gives patient-run (public) apps persistent access through dynamic client registration, not refresh tokens.
        "dynamic_registration": True,
    },
    "cerner": {
        "label": "Oracle Health", "portal": "patient portal",
        "sandbox_base": "https://fhir-myrecord.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d",
        "sandbox_hint": "Oracle Health sandbox test patient: nancysmart / Cerner01",
        "scopes": USCDI_SCOPES,
    },
    "athena": {
        "label": "athenahealth", "portal": "athenahealth patient portal",
        "sandbox_base": "https://api.preview.platform.athenahealth.com/fhir/r4",
        "sandbox_hint": "Use a synthetic patient from your athenahealth developer console",
        "scopes": USCDI_SCOPES,
    },
    "healow": {
        "label": "eClinicalWorks", "portal": "healow",
        # eClinicalWorks has no shared sandbox: each developer is given a sandbox practice. Connect to it as a
        # custom FHIR server (its fhir4.healow.com/fhir/r4/<code> address and your client ID).
        "sandbox_base": None,
        "sandbox_hint": "eClinicalWorks gives each developer a sandbox practice; connect to it under Custom FHIR server",
        "scopes": USCDI_SCOPES,
    },
    "va": {
        "label": "VA Lighthouse", "portal": "VA.gov",
        "sandbox_base": "https://sandbox-api.va.gov/services/fhir/v0/r4",
        "sandbox_hint": "Use the test veteran credentials from your VA developer account",
        "scopes": USCDI_SCOPES,
    },
    "smart-health-it": {
        "label": "SMART Health IT", "portal": "SMART Launcher",
        "sandbox_base": "https://launch.smarthealthit.org/v/r4/sim/WzMsICIiLCAiIiwgIkFVVE8iLCAwLCAwLCAwLCAiIiwgIiIsICIiLCAiIiwgIiIsICIiLCAiIiwgMCwgMSwgIiJd/fhir",
        "sandbox_hint": "Pick any synthetic patient in the SMART launcher (no password)",
        "scopes": "launch/patient openid fhirUser offline_access patient/*.read",
    },
}


@lru_cache(maxsize=1)
def _institutions() -> tuple[dict[str, Any], ...]:
    out: list[dict[str, Any]] = []
    for path in sorted((config.APP_DIR / "data" / "institutions").glob("*.json")):
        with open(path, encoding="utf-8") as fh:
            out.extend(json.load(fh))
    return tuple(out)


@lru_cache(maxsize=1)
def _haystacks() -> tuple[tuple[str, dict[str, Any]], ...]:
    """Lower-cased search text per institution, built once (the directory has ~20,000 entries)."""
    return tuple((" ".join([inst["name"], inst.get("network") or "", inst.get("location") or "", *inst.get("places", ()),
                            inst.get("portal") or "", PLATFORMS.get(inst["platform"], {}).get("label", "")]).lower(), inst)
                 for inst in _institutions())


@lru_cache(maxsize=1)
def _by_id() -> dict[str, dict[str, Any]]:
    # Ids merged into another entry when the directory was refreshed still resolve (saved connections use them).
    out = {old: i for i in _institutions() for old in i.get("former_ids", ())}
    out.update({i["id"]: i for i in _institutions()})
    return out


def get_institution(inst_id: str) -> Optional[dict[str, Any]]:
    inst = _by_id().get(inst_id)
    return dict(inst) if inst else None


def search(q: Optional[str] = None, platform: Optional[str] = None, limit: int = 25) -> dict[str, Any]:
    if q and q.strip():
        term = q.strip().lower()
        words = term.split()
        scored = []
        for hay, inst in _haystacks():
            if platform and inst["platform"] != platform:
                continue
            if not all(w in hay for w in words):
                continue
            name = inst["name"].lower()
            score = 0 if name.startswith(term) else 1 if any(p.startswith(term) for p in name.split()) else 2
            scored.append((score, 0 if inst.get("featured") else 1, inst["name"], inst))
        scored.sort(key=lambda s: s[:3])
        items = [s[3] for s in scored]
    else:
        items = sorted((i for i in _institutions() if not platform or i["platform"] == platform),
                       key=lambda i: (not i.get("featured"), i["name"]))
    return {"total": len(items), "results": items[:limit]}


def featured(limit: int = 12) -> list[dict[str, Any]]:
    picks = [i for i in _institutions() if i.get("featured")]
    # Put a mix of vendors first so the grid shows breadth.
    seen, first, rest = set(), [], []
    for inst in picks:
        (first if inst["platform"] not in seen else rest).append(inst)
        seen.add(inst["platform"])
    return (first + rest)[:limit]


def stats() -> dict[str, int]:
    out: dict[str, int] = {}
    for i in _institutions():
        out[i["platform"]] = out.get(i["platform"], 0) + 1
    return out
